"""
Tests for the statistical analysis module.

Generated by Claude Opus 4.6
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from src.analysis.statistical_analysis import (
    METRICS,
    analyse_histories,
    analyse_metric,
    clean_history,
    cohens_d,
    effect_size_label,
    remove_outliers_zscore,
    shapiro_wilk_test,
    welch_ttest,
)

# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────


def _make_history(cpu_values, gpu=0.0, ane=0.0, dram=0.0, time=0.0):
    """Build a history list from CPU values (shorthand for tests)."""
    return [
        {
            "i": i,
            "cpu_mj": v,
            "gpu_mj": gpu,
            "ane_mj": ane,
            "dram_mj": dram,
            "time_s": time,
        }
        for i, v in enumerate(cpu_values)
    ]


# ──────────────────────────────────────────────────────────────────────────────
# remove_outliers_zscore
# ──────────────────────────────────────────────────────────────────────────────


@pytest.mark.unit
class TestRemoveOutliersZscore:
    def test_no_outliers(self):
        values = [10.0, 11.0, 10.5, 10.2, 10.8]
        result = remove_outliers_zscore(values)
        assert result == values

    def test_extreme_outlier_removed(self):
        values = [10.0, 10.1, 10.2, 10.0, 10.1] * 6 + [500.0]
        result = remove_outliers_zscore(values)
        assert 500.0 not in result
        assert len(result) == 30

    def test_empty_list(self):
        assert remove_outliers_zscore([]) == []

    def test_single_element(self):
        assert remove_outliers_zscore([5.0]) == [5.0]

    def test_identical_values(self):
        values = [3.0, 3.0, 3.0, 3.0]
        assert remove_outliers_zscore(values) == values

    def test_two_elements(self):
        values = [1.0, 2.0]
        result = remove_outliers_zscore(values)
        assert result == values


# ──────────────────────────────────────────────────────────────────────────────
# shapiro_wilk_test
# ──────────────────────────────────────────────────────────────────────────────


@pytest.mark.unit
class TestShapiroWilk:
    def test_normal_data_passes(self):
        rng = np.random.default_rng(42)
        values = rng.normal(loc=10.0, scale=1.0, size=50).tolist()
        stat, p, is_normal = shapiro_wilk_test(values)
        assert is_normal is True
        assert p > 0.05

    def test_too_few_samples(self):
        stat, p, is_normal = shapiro_wilk_test([1.0, 2.0])
        assert math.isnan(stat)
        assert is_normal is False


# ──────────────────────────────────────────────────────────────────────────────
# welch_ttest
# ──────────────────────────────────────────────────────────────────────────────


@pytest.mark.unit
class TestWelchTtest:
    def test_significantly_different_samples(self):
        rng = np.random.default_rng(42)
        a = rng.normal(loc=10, scale=0.5, size=50).tolist()
        b = rng.normal(loc=15, scale=0.5, size=50).tolist()
        t, p, sig = welch_ttest(a, b)
        assert sig is True
        assert p < 0.05

    def test_identical_samples_not_significant(self):
        values = [10.0, 10.1, 10.2, 10.0, 10.1]
        t, p, sig = welch_ttest(values, values)
        assert sig is False

    def test_too_few_samples(self):
        t, p, sig = welch_ttest([1.0], [2.0])
        assert math.isnan(t)
        assert sig is False


# ──────────────────────────────────────────────────────────────────────────────
# cohens_d
# ──────────────────────────────────────────────────────────────────────────────


@pytest.mark.unit
class TestCohensD:
    def test_large_effect(self):
        a = [10.0, 10.1, 10.2, 10.0, 10.1]
        b = [20.0, 20.1, 20.2, 20.0, 20.1]
        d = cohens_d(a, b)
        assert abs(d) > 0.8

    def test_no_effect(self):
        values = [10.0, 10.1, 10.2, 10.0, 10.1]
        d = cohens_d(values, values)
        assert abs(d) < 0.01

    def test_identical_values_returns_zero(self):
        a = [5.0, 5.0, 5.0]
        b = [5.0, 5.0, 5.0]
        assert cohens_d(a, b) == 0.0


# ──────────────────────────────────────────────────────────────────────────────
# effect_size_label
# ──────────────────────────────────────────────────────────────────────────────


@pytest.mark.unit
class TestEffectSizeLabel:
    @pytest.mark.parametrize(
        ("d", "expected"),
        [
            (0.0, "negligible"),
            (0.1, "negligible"),
            (0.19, "negligible"),
            (0.2, "small"),
            (0.3, "small"),
            (0.5, "medium"),
            (0.79, "medium"),
            (0.8, "large"),
            (2.0, "large"),
            (-0.5, "medium"),
            (-1.0, "large"),
        ],
    )
    def test_labels(self, d, expected):
        assert effect_size_label(d) == expected


# ──────────────────────────────────────────────────────────────────────────────
# clean_history
# ──────────────────────────────────────────────────────────────────────────────


@pytest.mark.unit
class TestCleanHistory:
    def test_no_outliers(self):
        history = _make_history([10.0, 10.1, 10.2, 10.0, 10.1])
        cleaned = clean_history(history)
        assert len(cleaned) == 5

    def test_removes_extreme_outlier(self):
        values = [10.0] * 30 + [500.0]
        history = _make_history(values)
        cleaned = clean_history(history)
        assert len(cleaned) == 30
        assert all(e["cpu_mj"] != 500.0 for e in cleaned)

    def test_indices_renumbered(self):
        values = [10.0] * 20 + [500.0] + [10.0] * 10
        history = _make_history(values)
        cleaned = clean_history(history)
        for idx, entry in enumerate(cleaned):
            assert entry["i"] == idx

    def test_empty_history(self):
        assert clean_history([]) == []

    def test_single_entry(self):
        history = _make_history([10.0])
        assert len(clean_history(history)) == 1


# ──────────────────────────────────────────────────────────────────────────────
# analyse_metric
# ──────────────────────────────────────────────────────────────────────────────


@pytest.mark.unit
class TestAnalyseMetric:
    def test_returns_expected_keys(self):
        rng = np.random.default_rng(42)
        a = rng.normal(10, 1, 30).tolist()
        b = rng.normal(10, 1, 30).tolist()
        result = analyse_metric(a, b, "cpu_mj")

        expected_keys = {
            "metric",
            "n_a",
            "n_b",
            "mean_a",
            "mean_b",
            "mean_diff",
            "shapiro_a",
            "shapiro_b",
            "welch_ttest",
            "cohens_d",
            "effect_size",
            "sample_size_ok",
        }
        assert set(result.keys()) == expected_keys

    def test_sample_size_ok_when_large(self):
        rng = np.random.default_rng(42)
        a = rng.normal(10, 1, 30).tolist()
        b = rng.normal(10, 1, 30).tolist()
        result = analyse_metric(a, b, "cpu_mj")
        assert result["sample_size_ok"] is True

    def test_sample_size_not_ok_when_small(self):
        result = analyse_metric([1.0, 2.0, 3.0], [4.0, 5.0, 6.0], "cpu_mj")
        assert result["sample_size_ok"] is False


# ──────────────────────────────────────────────────────────────────────────────
# analyse_histories
# ──────────────────────────────────────────────────────────────────────────────


@pytest.mark.unit
class TestAnalyseHistories:
    def test_full_analysis_pipeline(self):
        rng = np.random.default_rng(42)
        history_a = [
            {
                "i": i,
                "cpu_mj": rng.normal(10, 0.5),
                "gpu_mj": rng.normal(5, 0.3),
                "ane_mj": rng.normal(2, 0.1),
                "dram_mj": rng.normal(1, 0.05),
                "time_s": rng.normal(0.1, 0.01),
            }
            for i in range(30)
        ]
        history_b = [
            {
                "i": i,
                "cpu_mj": rng.normal(10, 0.5),
                "gpu_mj": rng.normal(5, 0.3),
                "ane_mj": rng.normal(2, 0.1),
                "dram_mj": rng.normal(1, 0.05),
                "time_s": rng.normal(0.1, 0.01),
            }
            for i in range(30)
        ]

        result = analyse_histories(history_a, history_b)

        assert "raw_sizes" in result
        assert "cleaned_sizes" in result
        assert "outliers_removed" in result
        assert "cleaned_a" in result
        assert "cleaned_b" in result
        assert "metrics" in result
        assert set(result["metrics"].keys()) == set(METRICS)

    def test_cleaned_histories_returned(self):
        history = _make_history([10.0] * 30 + [500.0])
        result = analyse_histories(history, history)
        assert len(result["cleaned_a"]) < len(history)
        assert result["outliers_removed"]["a"] > 0
