# Copy-Paste from https://github.com/astral-sh/ruff-pre-commit
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.15.4
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
      exclude: ^src/examples/
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
      exclude: ^src/examples/
- repo: local
  hooks:
    - id: block-example-edits
      name: block example file commits
      entry: python scripts/block_example_edits.py
      language: python
      files: ^src/examples/