"""
Statistical analysis module for energy measurement data.

Implements the Part 2 methodology from Luis Cruz's scientific guide:
- Outlier detection and removal (Z-score, 3σ rule)
- Shapiro-Wilk normality test
- Welch's t-test for statistical significance
- Cohen's d for effect size

Generated by Claude Opus 4.6
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
from scipy import stats

if TYPE_CHECKING:
    import pandas as pd

# Minimum acceptable sample size after cleaning (from the guide)
MIN_SAMPLE_SIZE = 25

# Z-score threshold for outlier removal (3σ rule)
ZSCORE_THRESHOLD = 3

# Significance level for statistical tests
ALPHA = 0.05

# Metrics to analyse
METRICS = ("cpu_mj", "gpu_mj", "ane_mj", "dram_mj", "time_s")


def remove_outliers_zscore(
    values: list[float], threshold: float = ZSCORE_THRESHOLD
) -> list[float]:
    """
    Remove outliers from a list of values using the Z-score method (3σ rule).

    A data point is considered an outlier if |x̄ - x| > threshold * s,
    where x̄ is the sample mean and s is the standard deviation.

    Inputs
    ------
        values: List of numeric values to clean.
        threshold: Number of standard deviations beyond which a value is
                   considered an outlier (default: 3).

    Returns
    -------
        A new list containing only values within the threshold.
    """
    if len(values) < 2:
        return list(values)

    arr = np.array(values, dtype=float)
    mean = np.mean(arr)
    std = np.std(arr, ddof=1)

    if std == 0:
        return list(values)

    return [x for x in values if abs(mean - x) <= threshold * std]


def shapiro_wilk_test(values: list[float]) -> tuple[float, float, bool]:
    """
    Run the Shapiro-Wilk normality test on a sample.

    Inputs
    ------
        values: List of numeric values to test.

    Returns
    -------
        A tuple (statistic, p_value, is_normal) where is_normal is True
        when p_value > ALPHA (i.e., we cannot reject normality).
    """
    if len(values) < 3:
        return (float("nan"), float("nan"), False)

    arr = np.array(values, dtype=float)
    if np.ptp(arr) == 0:
        # All values identical — trivially normal, skip scipy to avoid warning
        return (1.0, 1.0, True)

    # Shapiro-Wilk is unreliable for N > 5000; subsample deterministically
    if len(arr) > 5000:
        rng = np.random.default_rng(seed=42)
        arr = rng.choice(arr, size=5000, replace=False)

    stat, p_value = stats.shapiro(arr)
    return (float(stat), float(p_value), bool(p_value > ALPHA))


def welch_ttest(
    sample_a: list[float], sample_b: list[float]
) -> tuple[float, float, bool]:
    """
    Run a two-tailed Welch's t-test comparing two independent samples.

    Inputs
    ------
        sample_a: First sample (e.g., measurements with code smell).
        sample_b: Second sample (e.g., measurements without code smell).

    Returns
    -------
        A tuple (t_statistic, p_value, is_significant) where is_significant
        is True when p_value < ALPHA.
    """
    if len(sample_a) < 2 or len(sample_b) < 2:
        return (float("nan"), float("nan"), False)

    a = np.array(sample_a, dtype=float)
    b = np.array(sample_b, dtype=float)
    if np.ptp(a) == 0 or np.ptp(b) == 0:
        # At least one sample has zero variance — t-test is undefined
        is_different = bool(np.mean(a) != np.mean(b))
        return (0.0, 1.0 if not is_different else 0.0, is_different)

    t_stat, p_value = stats.ttest_ind(sample_a, sample_b, equal_var=False)
    return (float(t_stat), float(p_value), bool(p_value < ALPHA))


def cohens_d(sample_a: list[float], sample_b: list[float]) -> float:
    """
    Compute Cohen's d effect size between two samples.

    Uses the pooled standard deviation:
        d = (mean_a - mean_b) / sqrt((std_a² + std_b²) / 2)

    Inputs
    ------
        sample_a: First sample.
        sample_b: Second sample.

    Returns
    -------
        Cohen's d value. Interpretation:
        |d| < 0.2 → small effect
        |d| ~ 0.5 → medium effect
        |d| > 0.8 → large effect
    """
    a = np.array(sample_a, dtype=float)
    b = np.array(sample_b, dtype=float)

    if np.ptp(a) == 0 and np.ptp(b) == 0:
        return 0.0

    std_a = np.std(a, ddof=1)
    std_b = np.std(b, ddof=1)
    pooled_std = np.sqrt((std_a**2 + std_b**2) / 2)

    if pooled_std == 0:
        return 0.0

    return float((np.mean(a) - np.mean(b)) / pooled_std)


def effect_size_label(d: float) -> str:
    """Return a human-readable label for a Cohen's d value."""
    abs_d = abs(d)
    if abs_d < 0.2:
        return "negligible"
    if abs_d < 0.5:
        return "small"
    if abs_d < 0.8:
        return "medium"
    return "large"


def clean_history(history: list[dict]) -> list[dict]:
    """
    Remove outliers from an energy measurement history.

    Applies Z-score outlier removal independently to each metric
    (cpu_mj, gpu_mj, ane_mj, dram_mj). An entry is kept only if
    ALL its metric values pass the Z-score test.

    Inputs
    ------
        history: List of dicts with keys i, cpu_mj, gpu_mj, ane_mj, dram_mj.

    Returns
    -------
        A new list of dicts with outliers removed and indices re-numbered.
    """
    if len(history) < 2:
        return list(history)

    # For each metric, compute mean/std and determine which indices are outliers
    outlier_indices: set[int] = set()

    for metric in METRICS:
        values = [entry[metric] for entry in history]
        arr = np.array(values, dtype=float)
        mean = np.mean(arr)
        std = np.std(arr, ddof=1)

        if std == 0:
            continue

        for idx, val in enumerate(values):
            if abs(mean - val) > ZSCORE_THRESHOLD * std:
                outlier_indices.add(idx)

    # Keep only non-outlier entries, re-number them
    cleaned = []
    for idx, entry in enumerate(history):
        if idx not in outlier_indices:
            new_entry = dict(entry)
            new_entry["i"] = len(cleaned)
            cleaned.append(new_entry)

    return cleaned


def analyse_metric(
    values_a: list[float], values_b: list[float], metric_name: str
) -> dict:
    """
    Run the full statistical analysis pipeline on a single metric.

    Inputs
    ------
        values_a: Metric values from sample A (with code smell).
        values_b: Metric values from sample B (without code smell).
        metric_name: Name of the metric being analysed.

    Returns
    -------
        A dict containing all analysis results for this metric.
    """
    shapiro_a_stat, shapiro_a_p, normal_a = shapiro_wilk_test(values_a)
    shapiro_b_stat, shapiro_b_p, normal_b = shapiro_wilk_test(values_b)

    t_stat, t_p, significant = welch_ttest(values_a, values_b)
    d = cohens_d(values_a, values_b)

    mean_a = float(np.mean(values_a)) if values_a else float("nan")
    mean_b = float(np.mean(values_b)) if values_b else float("nan")

    return {
        "metric": metric_name,
        "n_a": len(values_a),
        "n_b": len(values_b),
        "mean_a": mean_a,
        "mean_b": mean_b,
        "mean_diff": mean_a - mean_b,
        "shapiro_a": {
            "statistic": shapiro_a_stat,
            "p_value": shapiro_a_p,
            "normal": normal_a,
        },
        "shapiro_b": {
            "statistic": shapiro_b_stat,
            "p_value": shapiro_b_p,
            "normal": normal_b,
        },
        "welch_ttest": {
            "t_statistic": t_stat,
            "p_value": t_p,
            "significant": significant,
        },
        "cohens_d": d,
        "effect_size": effect_size_label(d),
        "sample_size_ok": len(values_a) >= MIN_SAMPLE_SIZE
        and len(values_b) >= MIN_SAMPLE_SIZE,
    }


def analyse_histories(history_a: list[dict], history_b: list[dict]) -> dict:
    """
    Run the full statistical analysis on two energy measurement histories.

    This is the main entry point. It:
    1. Cleans both histories (outlier removal)
    2. Runs Shapiro-Wilk, Welch's t-test, and Cohen's d on each metric
    3. Returns a comprehensive analysis report

    Inputs
    ------
        history_a: Raw history for sample A (with code smell).
        history_b: Raw history for sample B (without code smell).

    Returns
    -------
        A dict with keys:
        - raw_sizes: original sample sizes
        - cleaned_sizes: sample sizes after outlier removal
        - outliers_removed: number of outliers removed per sample
        - cleaned_a: cleaned history A
        - cleaned_b: cleaned history B
        - metrics: dict of metric_name → analysis results
    """
    cleaned_a = clean_history(history_a)
    cleaned_b = clean_history(history_b)

    metrics_results = {}
    for metric in METRICS:
        values_a = [entry[metric] for entry in cleaned_a]
        values_b = [entry[metric] for entry in cleaned_b]
        metrics_results[metric] = analyse_metric(values_a, values_b, metric)

    return {
        "raw_sizes": {"a": len(history_a), "b": len(history_b)},
        "cleaned_sizes": {"a": len(cleaned_a), "b": len(cleaned_b)},
        "outliers_removed": {
            "a": len(history_a) - len(cleaned_a),
            "b": len(history_b) - len(cleaned_b),
        },
        "cleaned_a": cleaned_a,
        "cleaned_b": cleaned_b,
        "metrics": metrics_results,
    }


def generate_pr_report(
    df_with: pd.DataFrame,
    df_without: pd.DataFrame,
    profiler: str,
    data_type: str,
) -> str:
    """
    Generate a markdown PR report comparing energy with and without a code smell.

    The report includes per-metric descriptive statistics (mean, median, std),
    Welch's t-test p-values, Cohen's d effect sizes, and a verdict section
    suitable for a pull-request description.

    Inputs
    ------
        df_with: Combined DataFrame of measurements *with* the code smell.
        df_without: Combined DataFrame of measurements *without* the code smell.
        profiler: Name of the profiler used (e.g. "mac", "carbon").
        data_type: "cleaned" or "raw".

    Returns
    -------
        A markdown-formatted string.
    """
    lines: list[str] = []
    lines.append(f"## Energy Impact Report \u2014 `{profiler}` ({data_type})")
    lines.append("")
    lines.append("|  | Value |")
    lines.append("|---|---|")
    lines.append(f"| Profiler | `{profiler}` |")
    lines.append(f"| Data type | `{data_type}` |")
    lines.append(f"| Samples (with smell) | {len(df_with)} |")
    lines.append(f"| Samples (without smell) | {len(df_without)} |")
    lines.append(f"| Significance level (\u03b1) | {ALPHA} |")
    lines.append("")

    lines.append("### Results per metric")
    lines.append("")
    col_headers = [
        "Metric",
        "Mean (smell)",
        "Median (smell)",
        "Std (smell)",
        "Mean (no smell)",
        "Median (no smell)",
        "Std (no smell)",
        "\u0394 mean",
        "p-value (Welch)",
        "Cohen\u2019s d",
        "Effect",
        "Significant?",
    ]
    lines.append("| " + " | ".join(col_headers) + " |")
    lines.append("|" + "|".join([":---:"] * len(col_headers)) + "|")

    verdicts: list[str] = []
    for metric in METRICS:
        if metric not in df_with.columns or metric not in df_without.columns:
            continue

        vals_with = remove_outliers_zscore(df_with[metric].dropna().tolist())
        vals_without = remove_outliers_zscore(df_without[metric].dropna().tolist())

        if len(vals_with) < 2 or len(vals_without) < 2:
            continue

        arr_with = np.array(vals_with)
        arr_without = np.array(vals_without)

        mean_with = float(np.mean(arr_with))
        mean_without = float(np.mean(arr_without))
        median_with = float(np.median(arr_with))
        median_without = float(np.median(arr_without))
        std_with = float(np.std(arr_with, ddof=1))
        std_without = float(np.std(arr_without, ddof=1))

        # Positive delta = removing the smell reduces energy
        delta = (
            (mean_with - mean_without) / mean_with * 100
            if mean_with != 0
            else float("nan")
        )

        _, p_val, significant = welch_ttest(vals_with, vals_without)
        d = cohens_d(vals_with, vals_without)
        effect = effect_size_label(d)
        sig_mark = "\u2705 yes" if significant else "no"
        delta_str = f"{delta:+.2f}%" if not np.isnan(delta) else "N/A"

        # For the carbon profiler, ane_mj actually stores the CO2 equivalent
        display_metric = (
            "co2_eq" if (profiler == "carbon" and metric == "ane_mj") else metric
        )

        unit = "g CO₂eq" if (profiler == "carbon" and metric == "ane_mj") else "mJ"

        row = [
            f"`{display_metric}`",
            f"{mean_with:.4f} {unit}",
            f"{median_with:.4f} {unit}",
            f"{std_with:.4f} {unit}",
            f"{mean_without:.4f} {unit}",
            f"{median_without:.4f} {unit}",
            f"{std_without:.4f} {unit}",
            delta_str,
            f"{p_val:.4f}",
            f"{d:+.3f}",
            effect,
            sig_mark,
        ]
        lines.append("| " + " | ".join(row) + " |")

        if significant and abs(d) >= 0.2:
            direction = "lower" if mean_without < mean_with else "higher"
            verdicts.append(
                f"- **`{display_metric}`**: removing the smell leads to **{abs(delta):.1f}% {direction}**"
                f" energy consumption (Cohen\u2019s d\u2009=\u2009{d:+.3f}, {effect} effect)."
            )

    lines.append("")
    lines.append(
        "> **\u0394 mean** = (mean\\_with \u2212 mean\\_without) / mean\\_with \u00d7 100. "
        "A positive value means removing the smell reduces energy consumption."
    )
    lines.append("")

    lines.append("### Verdict")
    lines.append("")
    if verdicts:
        lines.append("Statistically significant differences were found:")
        lines.append("")
        lines.extend(verdicts)
    else:
        lines.append(
            "No statistically significant, non-negligible differences were found. "
            "The code smell does not measurably impact energy consumption under the tested conditions."
        )
    lines.append("")

    lines.append("### Cohen\u2019s d reference")
    lines.append("")
    lines.append("| \\|d\\| range | Interpretation |")
    lines.append("|:---:|:---:|")
    lines.append("| < 0.2 | negligible |")
    lines.append("| 0.2 \u2013 0.5 | small |")
    lines.append("| 0.5 \u2013 0.8 | medium |")
    lines.append("| \u2265 0.8 | large |")
    lines.append("")

    return "\n".join(lines)
