"""
Statistical analysis module for energy measurement data.

Implements the Part 2 methodology from Luis Cruz's scientific guide:
- Outlier detection and removal (Z-score, 3σ rule)
- Shapiro-Wilk normality test
- Welch's t-test for statistical significance
- Cohen's d for effect size

Generated by Claude Opus 4.6
"""

from __future__ import annotations

import numpy as np
from scipy import stats

# Minimum acceptable sample size after cleaning (from the guide)
MIN_SAMPLE_SIZE = 25

# Z-score threshold for outlier removal (3σ rule)
ZSCORE_THRESHOLD = 3

# Significance level for statistical tests
ALPHA = 0.05

# Metrics to analyse
METRICS = ("cpu_mj", "gpu_mj", "ane_mj", "dram_mj")


def remove_outliers_zscore(
    values: list[float], threshold: float = ZSCORE_THRESHOLD
) -> list[float]:
    """
    Remove outliers from a list of values using the Z-score method (3σ rule).

    A data point is considered an outlier if |x̄ - x| > threshold * s,
    where x̄ is the sample mean and s is the standard deviation.

    Inputs
    ------
        values: List of numeric values to clean.
        threshold: Number of standard deviations beyond which a value is
                   considered an outlier (default: 3).

    Returns
    -------
        A new list containing only values within the threshold.
    """
    if len(values) < 2:
        return list(values)

    arr = np.array(values, dtype=float)
    mean = np.mean(arr)
    std = np.std(arr, ddof=1)

    if std == 0:
        return list(values)

    return [x for x in values if abs(mean - x) <= threshold * std]


def shapiro_wilk_test(values: list[float]) -> tuple[float, float, bool]:
    """
    Run the Shapiro-Wilk normality test on a sample.

    Inputs
    ------
        values: List of numeric values to test.

    Returns
    -------
        A tuple (statistic, p_value, is_normal) where is_normal is True
        when p_value > ALPHA (i.e., we cannot reject normality).
    """
    if len(values) < 3:
        return (float("nan"), float("nan"), False)

    stat, p_value = stats.shapiro(values)
    return (float(stat), float(p_value), bool(p_value > ALPHA))


def welch_ttest(
    sample_a: list[float], sample_b: list[float]
) -> tuple[float, float, bool]:
    """
    Run a two-tailed Welch's t-test comparing two independent samples.

    Inputs
    ------
        sample_a: First sample (e.g., measurements with code smell).
        sample_b: Second sample (e.g., measurements without code smell).

    Returns
    -------
        A tuple (t_statistic, p_value, is_significant) where is_significant
        is True when p_value < ALPHA.
    """
    if len(sample_a) < 2 or len(sample_b) < 2:
        return (float("nan"), float("nan"), False)

    t_stat, p_value = stats.ttest_ind(sample_a, sample_b, equal_var=False)
    return (float(t_stat), float(p_value), bool(p_value < ALPHA))


def cohens_d(sample_a: list[float], sample_b: list[float]) -> float:
    """
    Compute Cohen's d effect size between two samples.

    Uses the pooled standard deviation:
        d = (mean_a - mean_b) / sqrt((std_a² + std_b²) / 2)

    Inputs
    ------
        sample_a: First sample.
        sample_b: Second sample.

    Returns
    -------
        Cohen's d value. Interpretation:
        |d| < 0.2 → small effect
        |d| ~ 0.5 → medium effect
        |d| > 0.8 → large effect
    """
    a = np.array(sample_a, dtype=float)
    b = np.array(sample_b, dtype=float)

    std_a = np.std(a, ddof=1)
    std_b = np.std(b, ddof=1)
    pooled_std = np.sqrt((std_a**2 + std_b**2) / 2)

    if pooled_std == 0:
        return 0.0

    return float((np.mean(a) - np.mean(b)) / pooled_std)


def effect_size_label(d: float) -> str:
    """Return a human-readable label for a Cohen's d value."""
    abs_d = abs(d)
    if abs_d < 0.2:
        return "negligible"
    if abs_d < 0.5:
        return "small"
    if abs_d < 0.8:
        return "medium"
    return "large"


def clean_history(history: list[dict]) -> list[dict]:
    """
    Remove outliers from an energy measurement history.

    Applies Z-score outlier removal independently to each metric
    (cpu_mj, gpu_mj, ane_mj, dram_mj). An entry is kept only if
    ALL its metric values pass the Z-score test.

    Inputs
    ------
        history: List of dicts with keys i, cpu_mj, gpu_mj, ane_mj, dram_mj.

    Returns
    -------
        A new list of dicts with outliers removed and indices re-numbered.
    """
    if len(history) < 2:
        return list(history)

    # For each metric, compute mean/std and determine which indices are outliers
    outlier_indices: set[int] = set()

    for metric in METRICS:
        values = [entry[metric] for entry in history]
        arr = np.array(values, dtype=float)
        mean = np.mean(arr)
        std = np.std(arr, ddof=1)

        if std == 0:
            continue

        for idx, val in enumerate(values):
            if abs(mean - val) > ZSCORE_THRESHOLD * std:
                outlier_indices.add(idx)

    # Keep only non-outlier entries, re-number them
    cleaned = []
    for idx, entry in enumerate(history):
        if idx not in outlier_indices:
            new_entry = dict(entry)
            new_entry["i"] = len(cleaned)
            cleaned.append(new_entry)

    return cleaned


def analyse_metric(
    values_a: list[float], values_b: list[float], metric_name: str
) -> dict:
    """
    Run the full statistical analysis pipeline on a single metric.

    Inputs
    ------
        values_a: Metric values from sample A (with code smell).
        values_b: Metric values from sample B (without code smell).
        metric_name: Name of the metric being analysed.

    Returns
    -------
        A dict containing all analysis results for this metric.
    """
    shapiro_a_stat, shapiro_a_p, normal_a = shapiro_wilk_test(values_a)
    shapiro_b_stat, shapiro_b_p, normal_b = shapiro_wilk_test(values_b)

    t_stat, t_p, significant = welch_ttest(values_a, values_b)
    d = cohens_d(values_a, values_b)

    mean_a = float(np.mean(values_a)) if values_a else float("nan")
    mean_b = float(np.mean(values_b)) if values_b else float("nan")

    return {
        "metric": metric_name,
        "n_a": len(values_a),
        "n_b": len(values_b),
        "mean_a": mean_a,
        "mean_b": mean_b,
        "mean_diff": mean_a - mean_b,
        "shapiro_a": {
            "statistic": shapiro_a_stat,
            "p_value": shapiro_a_p,
            "normal": normal_a,
        },
        "shapiro_b": {
            "statistic": shapiro_b_stat,
            "p_value": shapiro_b_p,
            "normal": normal_b,
        },
        "welch_ttest": {
            "t_statistic": t_stat,
            "p_value": t_p,
            "significant": significant,
        },
        "cohens_d": d,
        "effect_size": effect_size_label(d),
        "sample_size_ok": len(values_a) >= MIN_SAMPLE_SIZE
        and len(values_b) >= MIN_SAMPLE_SIZE,
    }


def analyse_histories(history_a: list[dict], history_b: list[dict]) -> dict:
    """
    Run the full statistical analysis on two energy measurement histories.

    This is the main entry point. It:
    1. Cleans both histories (outlier removal)
    2. Runs Shapiro-Wilk, Welch's t-test, and Cohen's d on each metric
    3. Returns a comprehensive analysis report

    Inputs
    ------
        history_a: Raw history for sample A (with code smell).
        history_b: Raw history for sample B (without code smell).

    Returns
    -------
        A dict with keys:
        - raw_sizes: original sample sizes
        - cleaned_sizes: sample sizes after outlier removal
        - outliers_removed: number of outliers removed per sample
        - cleaned_a: cleaned history A
        - cleaned_b: cleaned history B
        - metrics: dict of metric_name → analysis results
    """
    cleaned_a = clean_history(history_a)
    cleaned_b = clean_history(history_b)

    metrics_results = {}
    for metric in METRICS:
        values_a = [entry[metric] for entry in cleaned_a]
        values_b = [entry[metric] for entry in cleaned_b]
        metrics_results[metric] = analyse_metric(values_a, values_b, metric)

    return {
        "raw_sizes": {"a": len(history_a), "b": len(history_b)},
        "cleaned_sizes": {"a": len(cleaned_a), "b": len(cleaned_b)},
        "outliers_removed": {
            "a": len(history_a) - len(cleaned_a),
            "b": len(history_b) - len(cleaned_b),
        },
        "cleaned_a": cleaned_a,
        "cleaned_b": cleaned_b,
        "metrics": metrics_results,
    }
